name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  ROLLNO: "01111104424"
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_KEY: ${{ secrets.EC2_KEY }}
  IMAGE_NAME: "app-code-01111104424"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Run tests
      run: |
        cd app
        npm test

    - name: Log in to DockerHub
      run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$ROLLNO .

    - name: Push Docker image
      run: |
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$ROLLNO

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: docker run -d --name app -p 80:3000 $DOCKERHUB_USERNAME/$IMAGE_NAME:$ROLLNO
